import assert from 'node:assert/strict';
const endpoint = 'http://127.0.0.1:8787/views';
const origin = 'https://abdul-manaan.github.io';
const read = async () => (await (await fetch(endpoint)).json()).count;
const initial = await read();
const responses = await Promise.all(Array.from({length: 30}, () => fetch(endpoint, {method: 'POST', headers: {Origin: origin}})));
assert(responses.every(r => r.ok));
const values = await Promise.all(responses.map(r => r.json()));
assert.equal(new Set(values.map(v => v.count)).size, 30);
assert.equal(await read(), initial + 30);
assert.equal(await read(), initial + 30);
assert.equal((await fetch(endpoint, {method:'POST',headers:{Origin:'https://example.org'}})).status,403);
assert.equal((await fetch(endpoint, {method:'POST'})).status,403);
assert.equal((await fetch(endpoint, {method:'DELETE',headers:{Origin:origin}})).status,405);
assert.equal((await fetch(endpoint+'/bad')).status,404);
const preflight=await fetch(endpoint,{method:'OPTIONS',headers:{Origin:origin}});
assert.equal(preflight.status,204);
assert.equal(preflight.headers.get('Access-Control-Allow-Origin'),origin);
assert.equal(await read(),initial+30);
console.log('PASS: 30 concurrent increments, read-only GET, CORS, preflight, invalid origins, methods and paths. Final count:', await read());
